### PR TITLE
add multipasta to bench

### PR DESCRIPTION
**Pull request by tim-smart**
Switches to testing against random binary data to better simulate binary uploads. Also increased chunk size to reflect node's high watermark.

Will leave this as a draft as I added a flake.nix which may not be wanted :)

### CODE REVIEW

**Comment by tunnckoCore** [comment]
First time hearing about `multipasta`, but anyway.

Noticing that you added it but not using it anywhere.

**Comment by mjackson** [comment]
Thanks for the PR, @tim-smart! I had totally forgotten to include multipasta in my benchmark.

Happy to include it, and to test against binary data in the benchmark. That seems like a good change.

But I'd rather not have the Nix files in this project since I don't really use it and this is my first time hearing about it.

**Comment by mjackson** [comment]
FYI I switched to benchmarking with random binary data in 834e4b26891e06df1eaed68e528b4c343789adf3, so you'll want to rebase. Should be less work for you tho in this PR.

**Comment by tim-smart** [comment]
Was looking into how smaller chunk sizes affect performance, and it seems there might be an issue somewhere:

image

**Comment by mjackson** [comment]
If the stream is very slow and it receives chunks smaller than the boundary the parser needs to buffer them and create a new `Uint8Array`. That may be what you're noticing. What chunk size are you using in your test? I changed the default chunk size to 64kb in the benchmarks per your recommendation :)

**Comment by tim-smart** [comment]
> If the stream is very slow and it receives chunks smaller than the boundary the parser needs to buffer them and create a new `Uint8Array`. That may be what you're noticing. What chunk size are you using in your test? I changed the default chunk size to 64kb in the benchmarks per your recommendation :)

I was trying 1024 and 2048 bytes. The slowdown was only occurring on the 5 large files test which is strange.

**Comment by mjackson** [comment]
Thanks for the info. I'll look into it 👍

**Comment by mjackson** [comment]
Holy smokes, multipasta is quick! Thanks again for the PR.

**Pull request merged**
